dist: trusty
language: java

sudo: true
addons:
  postgresql: "9.6"

before_build:
  - wget http://apache.claz.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar zxvf apache-maven-3.3.9-bin.tar.gz
  - chmod +x apache-maven-3.3.9/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r
  
cache:
  directories:
    - $HOME/.m2

before_script:
  - psql -c 'create database blog;' -U postgres
  - psql -c "create user blog with password 'blog';" -U postgres
  - psql -c 'grant all privileges on database blog to blog;' -U postgres

script: mvn install

jdk:
- oraclejdk8

branches:
  only:
  - master
  - development

notifications:
  email:
  - itpro@haksunkim.com

deploy:
  provider: releases
  api_key: $GIT_HUB_TOKEN
  file: $TRAVIS_BUILD_DIR/target/blog-middleware*.jar
  skip_cleanup: true
  on:
    tags: true